### ISSUE TITLE
Notify on Success?

### ISSUE THREAD

**Issue by andrewmartin** [dylang/grunt-notify#52]
Hey there. First off, great package, at least in theory! I am having some trouble getting notifications to appear. 

I was wondering if it was I was possibly doing something wrong, or if it's a system issue. 

I have had a few issues with Growl and Notification Center in the past, so it could be my system, but when I ran `grunt test` from the project master, the notification worked.

Is this designed to only show notifications on errors? I was hoping to get a little more granular control over it and show it on success of certain tasks (e.g. concat of a large vendor library when I make changes, etc).

Is there a way to override the Notification engine preference? I was thinking of just sidestepping Growl altogether, possibly.

Basic snippet from my Gruntfile:

```
# notify
notify:
  styl:
    options:
      message: "Stylus compiled."
  coffee:
    options:
      title: "Scripts compiled and uglified."
      message: "Coffee compiled."
```

Then on `watch`:

  grunt.initConfig

```
watch:
  options:
    spawn: true

  prod:
    files: ["**/*"]
    tasks: ["concurrent:prod"]

  coffee:
    files: ["**/*.coffee"]
    tasks: ["coffee", "concat", "uglify", "notify:coffee"]

  stylus:
    files: ["public/stylesheets/**/*.styl"]
    tasks: ["stylus", "concat:app", "notify:styl"]
```

Maybe there's some configuration step(s) I'm missing?
